<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">    
    <title><?=SITE_TITLE?></title>
    <link href="<?=URL?>/libs/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
    <link href="<?=URL?>/libs/select2-4.0.6-rc.1/dist/css/select2.min.css" rel="stylesheet"> 
    <link href="<?=URL?>/libs/select2-bootstrap-theme/dist/select2-bootstrap.min.css" rel="stylesheet"> 
    <link href="<?=URL?>/libs/alertifyjs/dist/css/alertify.css" rel="stylesheet">
    <link href="<?=URL?>/libs/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css" rel="stylesheet">
    <link href="<?=URL?>/css/bootstrap.min.css" rel="stylesheet" media="all">
    <link href="<?=URL?>/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="<?=URL?>/css/style.css?v=<?=filemtime('css/style.css');?>" rel="stylesheet" media="all">

    <link rel="apple-touch-icon" sizes="57x57" href="/images/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/images/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/images/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon/favicon-16x16.png">
    <link rel="manifest" href="/images/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/images/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">    
                 
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->     
</head>
<body>    

    <nav class="navbar navbar-admin mainmenu mb20" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>          
          <a class="navbar-brand" href="/"><i class="fa fa-sitemap fa-fw"></i> <?=SITE_NAME?></a>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">                      
            <li><a href="/tarefas">Tarefas</a><li>
            <li><a href="/projetos">Projetos</a><li>
            <li><a href="/usuarios">Usuarios</a><li>
          </ul>         

           <ul class="nav navbar-nav navbar-right">            
  
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-user fw"></i><?=$_SESSION['usuario_nome']?> <span class="caret"></span>                              
              </a>
              <ul class="dropdown-menu">
                <li><a href="<?=URL?>/sair"><i class="fa fa-power-off fw"></i> Sair</a></li>
              </ul>
            </li>
          </ul>

        </div><!-- /.navbar-collapse -->
      </div>
    </nav>


    <div class="container-fluid">

      <div class="panel panel-default">
        <div class="panel-body">
        <?php 
        $page = System\Router::pURL(0, 'tarefas');
        System\Page::loads($page, System\Config::getDefaultRouter());
        ?>
        </div>
      </div>
    </div>  
  
  <p class="text-center small text-muted"><?=SITE_FOOTER?></p>  

  <!-- <script src="//code.jquery.com/jquery.js"></script> -->
  <script src="<?=URL?>/libs/jquery/jquery-1.12.1.min.js"></script>
  <script src="<?=URL?>/js/bootstrap.min.js"></script>
  <script src="<?=URL?>/libs/datatables/datatables.min.js"></script>    
  <script src="<?=URL?>/libs/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>    
  <script src="<?=URL?>/libs/select2-4.0.6-rc.1/dist/js/select2.full.min.js"></script>
  <script src="<?=URL?>/libs/alertifyjs/dist/js/alertify.js"></script>
  <script src="https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js"></script>  
  <script src="<?=URL?>/js/script.min.js?v=<?=filemtime('js/script.min.js')?>"></script>
</body>
</html>